-- OmniEdge Professionals: environment setup
CREATE WAREHOUSE IF NOT EXISTS OMNIEDGE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS OMNIEDGE_REVOPS;
USE DATABASE OMNIEDGE_REVOPS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STG;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE WAREHOUSE OMNIEDGE_WH;